### ISSUE TITLE
Request instead of BaseRequest?

### ISSUE THREAD

**Issue by stuffmc** [ibm-bluemix-mobile-services/bms-clientsdk-swift-core#17]
Compiler warning says https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core/blob/master/Source/Network%20Requests/BMSURLSessionUtility.swift#L44 should use `Request` instead of `BaseRequest`.

**Comment by AnthonyOliveri** [comment]
At long last, this has been fixed in https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-core/pull/38. This warning will go away with the next release.
