### ISSUE TITLE
Does not compile in Swift 3

### ISSUE THREAD

**Issue by slizeray** [ibm-bluemix-mobile-services/bms-clientsdk-swift-core#2]
Hello,

I want to use the push service and it does not compile because of the bas core dependency.

Could you fix this? We need a fix urgently

Thanks,

Stéphane

**Comment by AnthonyOliveri** [comment]
Hi Stéphane,

Currently, BMSCore only supports Xcode 8 beta 4 and Xcode 8 beta 5. Support for Swift 3 in Xcode 8 GA is currently in progress and will be released soon.

**Comment by AnthonyOliveri** [comment]
BMSCore now supports Xcode 8 (8A218a) as of version 2.0.0.

**Comment by nicolas-miari** [comment]
Oops, I opened #13 before checking this (duplicate?)... 

Any plans to support Xcode 8.2.1 (8C1002)?

**Comment by AnthonyOliveri** [comment]
@nicolas-miari No worries. We can take care of this in issue #13  :-)

Xcode 8.2.1 is supported. It sounds like you are having a different issue related to Carthage.
